modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/impleri/mob-skills/issues"
license = "MIT"

[[mods]]
modId = "mobskills"
version = "${version}"
displayName = "Mob Skills"
authors = "impleri"
description = '''
A library mod that exposes KubeJS methods to control mob spawning.
'''
#logoFile = ""

[[dependencies.mobskills]]
modId = "playerskills"
mandatory = true
versionRange = "[1.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"
