modLoader = "javafml"
loaderVersion = "[40,41)"
issueTrackerURL = "https://github.com/impleri/mob-skills/issues"
license = "MIT"

[[mods]]
modId = "mobskills"
version = "${version}"
displayName = "Mob Skills"
authors = "impleri"
description = '''
A library mod that exposes KubeJS methods to control mob spawning.
'''
#logoFile = ""

[[dependencies.mobskills]]
modId = "playerskills"
mandatory = true
versionRange = "[1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "forge"
mandatory = true
versionRange = "[40,41)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "architectury"
mandatory = true
versionRange = "[4.0,)"
ordering = "AFTER"
side = "BOTH"
