modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/impleri/mob-skills/issues"
license = "MIT"

[[mods]]
modId = "mobskills"
version = "${version}"
displayName = "Mob Skills"
authors = "impleri"
description = '''
A library mod to control mob spawning using player-specific skills.
'''
#logoFile = ""

[[dependencies.mobskills]]
modId = "playerskills"
mandatory = true
versionRange = "[1.8.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mobskills]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "architectury"
mandatory = true
versionRange = "[6.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mobskills]]
modId = "kubejs"
mandatory = false
versionRange = "[1902.6,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.mobskills]]
modId = "crafttweaker"
mandatory = false
versionRange = "[10.1,)"
ordering = "BEFORE"
side = "BOTH"
