name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: impleri/automatic-skills/.github/workflows/build.yml@main

  publish:
    uses: impleri/automatic-skills/.github/workflows/publish.yml@main
    needs: build
    permissions:
      contents: write
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_TOKEN }}
      modrinth-id: ${{ secrets.MODRINTH_ID }}
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      curseforge-id: ${{ secrets.CURSEFORGE_ID }}
      curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
